[package]
name = "toolkitrs"
version = "0.1.11"
edition = "2021"
description = "A unified FFmpeg workflow CLI for batch media conversion, remuxing, and thumbnail embedding"
license = "MIT OR Apache-2.0"
repository = "https://github.com/seyallius/toolkitrs"
homepage = "https://github.com/seyallius/toolkitrs"
documentation = "https://docs.rs/toolkitrs"
readme = "README.md"
keywords = ["ffmpeg", "media", "cli", "batch", "video"]
categories = ["command-line-utilities", "multimedia::video", "multimedia::audio"]
exclude = ["bck/*", ".github/*", "bash/*"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
console = "0.16.4"
crossterm = "0.29.0"
ratatui = "0.30.2"
tempfile = "3.12"
thiserror = "2.0"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
